### ISSUE TITLE
Cron.matchDate returns always true when using weekdays and days of month

### ISSUE THREAD

**Issue by renzo-s** [P4sca1/cron-schedule#270]
Because of this line in matchDate: `(this.days.indexOf(day) !== -1 || this.weekdays.indexOf(weekday) !== -1)` an expression like `* * * * * 0,6` (Only on Saturday's or Sunday's) will always return true since `indexOf(day)` will always return true. I believe correct would be using logical AND instead of OR.

Thanks for the package, just what I was looking for. This behaviour is not hard to overwrite, just letting you know 👍 

Ref: https://github.com/P4sca1/cron-schedule/blob/777e7d37037f4fd1b088c393e3bb34e7fa330fc3/src/cron.ts#L538

**Comment by P4sca1** [comment]
Hello @renzo-s 👋

Thank you for your feedback. The expression 0-6 in the weekdays field will not result in only Saturdays or sundays, but will allow any weekday between 0 (Sunday) and 6 (Saturday), which includes 1 (Monday), 2 (Tuesday), …, which at the end is every weekday. 
If you only want to include Sunday and Saturday, use 0,6 instead (comma instead of dash).

The logic that either day of month or weekday needs to match, comes from this note from crontab.org:
> Note: The day of a command's execution can be specified by two  fields  --  day  of  month, and day of week.  If both fields are restricted (ie, aren't *), the command will  be run when either field matches the current time.

So you are right, that this check is wrong, when one of the fields is not restricted.

**Comment by renzo-s** [comment]
Hi Pascal, 🙈  damn that was a silly typo. I'm using `0,6` not `0-6`. Sorry for the confusion. Thanks for the quick reply.

In my own fix I just replaced the OR with an AND, but I had a hard time for coming up with a use case for why the brackets are there in the first place? Any example of that?
