### ISSUE TITLE
Cron Schedule Manager

### ISSUE THREAD

**Issue by afonsojramos** [P4sca1/cron-schedule#69]
Do you think an optional manager could be implemented? Such as this one (https://github.com/cfurst/CronJobManager), which is aimed at the `cron` package?

I think the implementation could be really simple and it would improve a lot with environments with multiple cron jobs.

I can help if you need.

**Comment by P4sca1** [comment]
I'm struggling wether the management of scheduled jobs is in the scope of this package.
I will consider it as a feature to add in the future, but I currently dont have much spare time. Feel free to create a pull request and I will take a look at it.

PS:
There is also the intention to move this package under a `cronjs` organization and further split this package into smaller packages:`@cronjs/parser`, `@cronjs/interval-based-scheduler`, ...
The idea is to also introduce new packages like `@cronjs/validator`. There could also be a `@cronjs/manager` package for what you have described.
However this process has not been completed yet, because of lack of time.

**Comment by afonsojramos** [comment]
You're right, maybe it should be placed under a different package!
